# Generated by Django 3.2.9 on 2021-12-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rummagerapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haul',
            old_name='diver_id',
            new_name='diver',
        ),
        migrations.RenameField(
            model_name='haul',
            old_name='dumpster_id',
            new_name='dumpster',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='haul_id',
            new_name='haul',
        ),
    ]
