# Generated by Django 3.2.9 on 2021-12-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rummagerapi', '0002_auto_20211206_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaulTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rummagerapi.haul')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rummagerapi.tag')),
            ],
        ),
    ]
