# Generated by Django 3.2.10 on 2022-01-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rummagerapi', '0003_auto_20211209_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haul',
            name='image_path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='haul',
            name='tags',
            field=models.ManyToManyField(related_name='hauls', to='rummagerapi.Tag'),
        ),
        migrations.AlterField(
            model_name='item',
            name='haul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rummagerapi.haul'),
        ),
    ]
